### ISSUE TITLE
Overlay Bug on Mobile View

### ISSUE THREAD

**Issue by lauragift21** [lauragift21/giftegwuenu.dev#167]
On mobile screen(s), the black-transparent overly that appears after clicking the Hamburger does not clear if try navigating to the "About" or "Contact" section. I recorded a video to explain it better: 

https://www.loom.com/share/7d5e3626dbdd4d1c857c390543327b7c

**Comment by TressOhi** [comment]
I created a pull request that should fix this

**Comment by lauragift21** [comment]
Thank you @TressOhi 😊
