### ISSUE TITLE
Bug: Animate-On-Scroll content overflow out of their parent

### ISSUE THREAD

**Issue by danBamikiya** [lauragift21/giftegwuenu.dev#214]
When a page containing animate-on-scroll content is scrolled fast, the last elements of the content 'hangs' for some seconds (the `transition-duration` which is `.6s`) out their parent. This isn't obvious when the page is scrolled at a 'normal' speed but is very obvious when scrolled at a relatively fast speed.

The pages affected:
- /speaking
- /writing (before the carbon ads display)

I'm not chanced to screen record the bug but it can be simulated in the following ways:
- /speaking
   1. By scrolling to the end of the page fast (its very obvious this way)
   2. By scrolling to the end of the page(at any speed), opening the browser dev-tools and turning off the following class rules of the last div child of the last `.past` element:
   ```
     -webkit-transform: translateZ(0);
     transform: translateZ(0);
  ```
     visual representations:
      Bug:
![image](https://user-images.githubusercontent.com/58262528/126572851-d7dfe8cf-c1fc-4460-8b3f-afc390319638.png)

    2nd Simulation:

![giftegwuenu-dev-website-bug-simulation-1](https://user-images.githubusercontent.com/58262528/126572579-829543bc-e78a-4d9c-ba12-a141d42b519a.png)

- /writing
    1. By scrolling to the end of the page fast (before the carbon ads display)
    2. By scrolling to the end of the page at any speed, deleting `carbon-ads` element, then scrolling very fast on this page
    3. By deleting `carbon-ads` element then turning off the following class rules of the last div child of the `.grid` element:
   ```
     -webkit-transform: translateZ(0);
     transform: translateZ(0);
  ```
   
    visual representations:
    Bug:
![image](https://user-images.githubusercontent.com/58262528/126573941-c1ef78d2-ea5c-422e-996e-364996777236.png)

    3rd Simulation:
![giftegwuenu-dev-website-bug-simulation-2](https://user-images.githubusercontent.com/58262528/126574149-a823c124-ba9e-4d15-8458-aa23629400df.png)

**Comment by lauragift21** [comment]
Thank you! I think I have seen this behavior but haven't had the time to check and fix it. 

Appreciate you reporting this

**Comment by danBamikiya** [comment]
You're welcome!
